[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "PyHTTPChat-Client"
version = "0.01"

[project.urls]
Homepage = "https://github.com/Env-Ir0n/PYHTTPCHAT-CLIENT"